### ISSUE TITLE
Error Publishing a local android container

### ISSUE THREAD

**Issue by fhkarczeski** [electrode-io/ern-container-publisher-maven#23]
Hi everyone,

Ever since this [PR](https://github.com/electrode-io/ern-container-publisher-maven/pull/22) got merged we have been unable to run our miniapps on Android with the `ern run-android` command, not sure if this is related but the timing seems to indicate that it is possible.

Also, today we tried to publish an Android container to a local Maven repository and we got the following error:
```
Ensuring that path is a container path 0s
An error occurred: Command failed: ./gradlew publish
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
 
FAILURE: Build failed with an exception.
 
* What went wrong:
A problem was found with the configuration of task ':lib:signReleasePublication' (type 'Sign').
- In plugin 'org.gradle.signing' type 'org.gradle.plugins.signing.Sign' property 'signatory.keyId' doesn't have a configured value.
     
Reason: This property isn't marked as optional and no value has been configured.
     
Possible solutions:
1. Assign a value to 'signatory.keyId'.
2. Mark property 'signatory.keyId' as optional.
     
Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#value_not_set for more details about this problem.
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insig
hts.
 
* Get more help at https://help.gradle.org
 
 BUILD FAILED in 9s
```

This is the command we are using:
`ern publish-container --containerPath CONTAINER_PATH -p maven -v 0.1.1 --platform android`

This command had also been working for us until the PR above got merged. Do you guys have any suggestions?

**Comment by rthic23** [comment]
@fhkarczeski `ern publish-container --containerPath CONTAINER_PATH -p maven -v 0.1.1 --platform android`
Please use ERN version >= 0.50.0 for the above command. 

Versions lesser than 0.50.0 please use the below command (Breaking change will be fixed soon in patch for previous versions)
`ern publish-container --containerPath CONTAINER_PATH -p ern-container-publisher-maven@1.0.5 -v 0.1.1 --platform android`

**Comment by fhkarczeski** [comment]
@Karthiccc23 , thanks for the response!

Running the command you suggested gives a different error:
```
 ___ _        _               _       _  _      _   _         
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v0.50.1] [Cauldron: -NONE-]

✖ An error occurred: Command failed: ./gradlew lib:uploadArchives
✖ 
✖ FAILURE: Build failed with an exception.
✖ 
✖ * Where:
✖ Build file '/private/var/folders/wp/wh3jhvy963x_6p4x7q2hhp3dkvk0f6/T/tmp-45835-3UPMIAW13kJK/lib/build.gradle' line: 44
✖ 
✖ * What went wrong:
✖ A problem occurred evaluating project ':lib'.
✖ > Plugin with id 'maven' not found.
✖ 
✖ * Try:
✖ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insig
hts.
✖ 
✖ * Get more help at https://help.gradle.org
✖ 
✖ BUILD FAILED in 14s
```

I am on v0.50.1, so my initial command should've been working?

**Comment by rthic23** [comment]
@fhkarczeski I was able to publish with the same command. Can you remove ~/.ern folder and run the command to reset the ERN.

**Comment by fhkarczeski** [comment]
@Karthiccc23,

Deleting the ~/.ern folder and running the `ern publish-container --containerPath CONTAINER_PATH -p maven -v 0.1.1 --platform android` worked. We are still having issues running our miniapps on both Android and iOS but I don't think it is related to this issue.

Thank you for the help!
